### ISSUE TITLE
RangeError: stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by antonbaumann** [who-wrote-that/cli#65]
calling
`wtf def LtiOutcomeUrlResource.java LtiOutcomeUrlResource`

https://github.com/ls1intum/Artemis/src/main/java/de/tum/in/www1/artemis/web/rest/LtiOutcomeUrlResource.java

**Comment by antonbaumann** [comment]
```
{ RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:359:14)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:272:13)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:154:17)
  cmd:
   'git show d041b99e1dcd9fa71ecb1f1b6a0635a06e122390 | grep Author' }
```
